### ISSUE TITLE
is it possible to rewrite it for different tracker

### ISSUE THREAD

**Issue by sonics007** [mancuniancol/plugin.video.t411#1]
is it possible to rewrite it for different tracker ?

**Comment by mancuniancol** [comment]
In theory yes.  But, this is my first version. Not sure that it is working 100%.

**Comment by sonics007** [comment]
what information do you need about pr.tracker to compilete another viewer

**Comment by mancuniancol** [comment]
The home page for start

**Comment by sonics007** [comment]
http://tracker.cztorrent.net/

**Comment by sonics007** [comment]
If you need anything else just let me know

**Comment by mancuniancol** [comment]
Don't worry I will.

**Comment by sonics007** [comment]
hi do you have any progress?

**Comment by mancuniancol** [comment]
About the Cztracker?

**Comment by sonics007** [comment]
yees

**Comment by mancuniancol** [comment]
I have it in my list. It may be I will have some time this week. It is relativity easy with the code that I have to write other viewers. My problem is my lack of spare time. :(

**Comment by mancuniancol** [comment]
I've checked the tracker, but it doesn't admit more registration and I don't have a valid account.  Then, i cannot write the viewer. Sorry.  I will close this issue.
