### ISSUE TITLE
Credenciales incorectas

### ISSUE THREAD

**Issue by jacoball** [mancuniancol/plugin.video.t411#3]
Hello , unable to connect to the service, I have an error message: Credenciales incorectas

Thanks for your help

**Comment by mancuniancol** [comment]
Could you check that you introduce your right username and password from t411 site?

**Comment by jacoball** [comment]
Hello , I 'm writing several times , I put the same time on T411 ... 
I have not problem on the site of T411 ... and always Credenciales incorectas on Kodi ?? 
I have to activate something on the T411 website ?? 
The User name and password is the one that allows me to log on the site?
Thanks for your help

**Comment by mancuniancol** [comment]
I will check that this weekend. It could be the site change something

**Comment by jacoball** [comment]
Hello , maybe I do not own the latest version .
I have 1.0.0 and I see ChangeLog , the latest is 1.0.2 . If you have
the or the link to download it ?

Thank you


2016-02-23 11:51 GMT+01:00 mancuniancol <notifications@github.com>:

**Comment by mancuniancol** [comment]
Releases 
https://github.com/mancuniancol/plugin.video.t411/archive/v1.0.2.zip

**Comment by jacoball** [comment]
Thank , i m sorry
i uninstall the 1.0.0 version and install a new add-on 1.0.0.2

but I still see 1.0.0.0 ???

join copy screen

maybe it s a correct version , just pb on the screen , i have the same
pb Credenciales incorectas


2016-02-23 12:24 GMT+01:00 mancuniancol <notifications@github.com>:

**Comment by mancuniancol** [comment]
If you are getting version 1.0.0 that means that you have the wrong version installed. 
Please, check this file and you will see that it is marked version 1.0.2

https://github.com/mancuniancol/plugin.video.t411/blob/master/addon.xml

**Comment by jacoball** [comment]
ok
but i uninstall from kodi V 1.0.0  and re install v 1.0.2


how install the old version
i go on add-on search / t411

it find media source t411 viewer , Enter / Uninstall  ...
after i go to install from zip , i take the new one ... after installation
Error message Credentiales ,,,
and i see i m already  with 1.0.0.0




2016-02-23 13:01 GMT+01:00 mancuniancol <notifications@github.com>:

**Comment by mancuniancol** [comment]
It is better if you erase the plugin.video.t411 in addons and userdata/addons

**Comment by mancuniancol** [comment]
I cannot help you if you don't have the latest version

**Comment by jacoball** [comment]
ok
it was impossible to remove it
i reset my all my kODI and reinstall all

now i have the last Version

but  already the same error message Credentiaes incorectas

Thanks

2016-02-23 13:24 GMT+01:00 mancuniancol <notifications@github.com>:

**Comment by jacoball** [comment]
Hi ,

i restart all , now i don t have anymore a message

Thanks


2016-02-23 14:28 GMT+01:00 jacob allouche <jacoballouche1926@gmail.com>:
